### ISSUE TITLE
cant add any bookmarks

### ISSUE THREAD

**Issue by cyber-vi** [kanishka-linux/reminiscence#67]
Im using firefox 88
I cant add bookmarks
I don't understand what the output means, so I cant tell you more about my problem

here is what my terminal looks like:

```
(venv) [user@browsing reminiscence]$ python manage.py runserver 127.0.0.1:8000 
Watching for file changes with StatReloader
INFO:django.utils.autoreload:Watching for file changes with StatReloader
Performing system checks...

System check identified some issues:

WARNINGS:
pages.GroupTable: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
	HINT: Configure the DEFAULT_AUTO_FIELD setting or the PagesConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
pages.Library: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
	HINT: Configure the DEFAULT_AUTO_FIELD setting or the PagesConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
pages.Tags: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
	HINT: Configure the DEFAULT_AUTO_FIELD setting or the PagesConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
pages.URLTags: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
	HINT: Configure the DEFAULT_AUTO_FIELD setting or the PagesConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.
pages.UserSettings: (models.W042) Auto-created primary key used when not defining a primary key type, by default 'django.db.models.AutoField'.
	HINT: Configure the DEFAULT_AUTO_FIELD setting or the PagesConfig.default_auto_field attribute to point to a subclass of AutoField, e.g. 'django.db.models.BigAutoField'.

System check identified 5 issues (0 silenced).
May 17, 2021 - 07:38:02
Django version 3.2.3, using settings 'reminiscence.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
"GET / HTTP/1.1" 200 4669
INFO:django.server:"GET / HTTP/1.1" 200 4669
"GET /static/css/bootstrap.min.css HTTP/1.1" 304 0
INFO:django.server:"GET /static/css/bootstrap.min.css HTTP/1.1" 304 0
"GET /static/folder.svg HTTP/1.1" 304 0
INFO:django.server:"GET /static/folder.svg HTTP/1.1" 304 0
"GET /static/menu.svg HTTP/1.1" 304 0
INFO:django.server:"GET /static/menu.svg HTTP/1.1" 304 0
"GET /user/bookmarks HTTP/1.1" 200 5623
INFO:django.server:"GET /user/bookmarks HTTP/1.1" 200 5623
476::INFO::vinanti::__start_fetching__: using backend: urllib for url : https://springmerchant.com/bigcommerce/psycopg2-virtualenv-install-pg_config-executable-not-found/
INFO:vinanti.vinanti:using backend: urllib for url : https://springmerchant.com/bigcommerce/psycopg2-virtualenv-install-pg_config-executable-not-found/
478::INFO::vinanti::__start_fetching__: 
Requesting url: https://springmerchant.com/bigcommerce/psycopg2-virtualenv-install-pg_config-executable-not-found/

INFO:vinanti.vinanti:
Requesting url: https://springmerchant.com/bigcommerce/psycopg2-virtualenv-install-pg_config-executable-not-found/

"POST /user/bookmarks HTTP/1.1" 200 5624
INFO:django.server:"POST /user/bookmarks HTTP/1.1" 200 5624
391::INFO::vinanti::__finished_task_postprocess__: 
completed: 1

INFO:vinanti.vinanti:
completed: 1

407::INFO::vinanti::__finished_task_postprocess__: arranging callback, task 0 https://springmerchant.com/bigcommerce/psycopg2-virtualenv-install-pg_config-executable-not-found/
INFO:vinanti.vinanti:arranging callback, task 0 https://springmerchant.com/bigcommerce/psycopg2-virtualenv-install-pg_config-executable-not-found/
DEBUG:pages.dbaccess:text/html ----> .html
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-1' coro=<Vinanti.__start_fetching__() done, defined at /home/user/reminiscence/venv/reminiscence/vinanti/vinanti.py:431> exception=SynchronousOnlyOperation('You cannot call this from an async context - use a thread or sync_to_async.')>
Traceback (most recent call last):
  File "/home/user/reminiscence/venv/reminiscence/vinanti/vinanti.py", line 509, in __start_fetching__
    self.__finished_task_postprocess__(session, netloc, onfinished,
  File "/home/user/reminiscence/venv/reminiscence/vinanti/vinanti.py", line 409, in __finished_task_postprocess__
    onfinished(task_num, url, result)
  File "/home/user/reminiscence/venv/reminiscence/pages/dbaccess.py", line 222, in url_fetch_completed
    row = Library.objects.create(usr=usr,
  File "/home/user/reminiscence/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/user/reminiscence/venv/lib/python3.9/site-packages/django/db/models/query.py", line 453, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/user/reminiscence/venv/lib/python3.9/site-packages/django/db/models/base.py", line 726, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/home/user/reminiscence/venv/lib/python3.9/site-packages/django/db/models/base.py", line 763, in save_base
    updated = self._save_table(
  File "/home/user/reminiscence/venv/lib/python3.9/site-packages/django/db/models/base.py", line 868, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/home/user/reminiscence/venv/lib/python3.9/site-packages/django/db/models/base.py", line 906, in _do_insert
    return manager._insert(
  File "/home/user/reminiscence/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/user/reminiscence/venv/lib/python3.9/site-packages/django/db/models/query.py", line 1270, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/home/user/reminiscence/venv/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1414, in execute_sql
    with self.connection.cursor() as cursor:
  File "/home/user/reminiscence/venv/lib/python3.9/site-packages/django/utils/asyncio.py", line 24, in inner
    raise SynchronousOnlyOperation(message)
django.core.exceptions.SynchronousOnlyOperation: You cannot call this from an async context - use a thread or sync_to_async.
"GET /user/bookmarks HTTP/1.1" 200 5623
INFO:django.server:"GET /user/bookmarks HTTP/1.1" 200 5623
"GET /user/bookmarks HTTP/1.1" 200 5623
INFO:django.server:"GET /user/bookmarks HTTP/1.1" 200 5623
"GET /static/js/jquery-3.3.1.min.js HTTP/1.1" 304 0
INFO:django.server:"GET /static/js/jquery-3.3.1.min.js HTTP/1.1" 304 0
"GET /static/js/popper.min.js HTTP/1.1" 304 0
INFO:django.server:"GET /static/js/popper.min.js HTTP/1.1" 304 0
"GET /static/js/bootstrap.min.js HTTP/1.1" 304 0
INFO:django.server:"GET /static/js/bootstrap.min.js HTTP/1.1" 304 0
"GET /static/js/bootbox.min.js HTTP/1.1" 304 0
INFO:django.server:"GET /static/js/bootbox.min.js HTTP/1.1" 304 0
"GET /static/js/main.js HTTP/1.1" 304 0
INFO:django.server:"GET /static/js/main.js HTTP/1.1" 304 0

```

**Comment by kanishka-linux** [comment]
can you try `VINANTI_BACKEND='aiohttp'` [here](https://github.com/kanishka-linux/reminiscence/blob/master/reminiscence/settings.py#L236).

If possible try docker image and see if it works.

I'll try to look into over the weekend.

And yes, if possible provide distro/OS information.

**Comment by cyber-vi** [comment]
I was using Fedora back then.
I am currently using Ubuntu and everything works well.
Thank you and sorry for the delayed response.
